{{- if .Values.webhooks.contributors.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-memory-svc.contributorsFullname" . }}
  labels:
    {{- include "ai-memory-svc.labels" . | nindent 4 }}
    app.kubernetes.io/component: contributors
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.webhooks.contributors.port | default 8080 }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "ai-memory-svc.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: contributors
{{- end }}
